require("neovide")
require("theprimeagen")

--local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
--if not vim.loop.fs_stat(lazypath) then
--    vim.fn.system(
--        {
--            "git",
--            "clone",
--            "--filter=blob:none",
--            "https://github.com/folke/lazy.nvim.git",
--            "--branch=stable", -- latest stable release
--            lazypath,
--        }
--    )
--end
--
--vim.opt.rtp:prepend(lazypath)
--
----// TODO: lets see about the lsp
--
--require("lazy").setup(
--    {
--        'mbbill/undotree',
--
--        { 'anuvyklack/animation.nvim', lazy = true },
--        { 'anuvyklack/middleclass',    lazy = true },
--        { 'nvim-lua/plenary.nvim',     lazy = true },
--
--        {
--            "anuvyklack/windows.nvim",
--            dependencies = {
--                "anuvyklack/middleclass",
--                "anuvyklack/animation.nvim"
--            },
--            config = function()
--                vim.o.winwidth = 10
--                vim.o.winminwidth = 10
--                vim.o.equalalways = false
--                require('windows').setup()
--            end
--        },
--
--        {
--            "folke/tokyonight.nvim",
--            lazy = false,    -- make sure we load this during startup if it is your main colorscheme
--            priority = 1000, -- make sure to load this before all the other start plugins
--            config = function()
--                -- load the colorscheme here
--                vim.cmd([[colorscheme tokyonight-night]])
--            end
--        },
--
--        -- init.lua:
--        {
--            'nvim-telescope/telescope.nvim',
--            tag = '0.1.5',
--            config = function()
--                require("telescope").setup()
--            end,
--            -- or                              , branch = '0.1.x',
--            dependencies = { 'nvim-lua/plenary.nvim' }
--        },
--
--        {
--            'nvim-treesitter/nvim-treesitter',
--            build = ':TSUpdate',
--        },
--
--        { 'tpope/vim-fugitive' },
--
--        {
--            "folke/todo-comments.nvim",
--            dependencies = { "nvim-lua/plenary.nvim" },
--            opts = {
--                -- your configuration comes here
--                -- or leave it empty to use the default settings
--                -- refer to the configuration section below
--            }
--        },
--
--        {
--            'williamboman/mason.nvim',
--            config = function()
--                require("mason").setup()
--            end,
--            lazy = off
--        },
--
--        {
--            'williamboman/mason-lspconfig.nvim',
--            dependencies = {
--                "williamboman/mason.nvim",
--            },
--            config = function()
--                require("mason").setup()
--            end
--        },
--
--        {
--            'neovim/nvim-lspconfig',
--            dependencies = {
--                "williamboman/mason.nvim",
--                "williamboman/mason-lspconfig.nvim",
--            },
--            config = function()
--                require("mason").setup()
--                require("mason-lspconfig").setup({
--                    ensure_installed = {
--                        "lua_ls",
--                    },
--                    handlers = {
--                        function(server_name) -- default handler (optional)
--                            require("lspconfig")[server_name].setup {}
--                        end,
--                    }
--                })
--                vim.diagnostic.config({
--                    -- update_in_insert = true,
--                    float = {
--                        focusable = false,
--                        style = "minimal",
--                        border = "rounded",
--                        source = "always",
--                        header = "",
--                        prefix = "",
--                    },
--                })
--            end
--        },
--
--    }
--)
